export const LOAD_GLOBAL_POST = 'LOAD_GLOBAL_POST';
export const LOAD_GLOBAL_POST_SUCCESS = 'LOAD_GLOBAL_POST_SUCCESS';
export const LOAD_GLOBAL_POST_FAILURE = 'LOAD_GLOBAL_POST_FAILURE';

export const LOAD_PERSONAL_POST = 'LOAD_PERSONAL_POST';
export const LOAD_PERSONAL_POST_SUCCESS = 'LOAD_PERSONAL_POST_SUCCESS';
export const LOAD_PERSONAL_POST_FAILURE = 'LOAD_PERSONAL_POST_FAILURE';

export const UPDATE_LIKE = 'UPDATE_LIKE';
export const UPDATE_LIKE_SUCCESS = 'UPDATE_LIKE_SUCCESS';
export const UPDATE_LIKE_FAILURE = 'UPDATE_LIKE_FAILURE';
