export const LOAD_POST = 'LOAD_POST';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE';

export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const LOAD_COUNT_COMMENTS_SUCCESS = 'LOAD_COUNT_COMMENTS_SUCCESS';

export const LOAD_MORE_COMMENTS = 'LOAD_MORE_COMMENTS';
export const LOAD_MORE_COMMENTS_SUCCESS = 'LOAD_MORE_COMMENTS_SUCCESS';

export const POST_COMMENT = 'POST_COMMENT';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
