export const LOAD_USER_INFO = 'LOAD_USER_INFO';
export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS';

export const LOAD_OWN_POST = 'LOAD_OWN_POST';
export const LOAD_OWN_POST_SUCCESS = 'LOAD_OWN_POST_SUCCESS';

export const LOAD_FAVORITE_POST = 'LOAD_FAVORITE_POST';
export const LOAD_FAVORITE_POST_SUCCESS = 'LOAD_FAVORITE_POST_SUCCESS';

export const FOLLOW = 'FOLLOW';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';

export const UNFOLLOW = 'UNFOLLOW';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
